=== Akash00226145/sorworkspace/DateTime.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                      targetNamespace="http://www.dates.com"
                      xmlns="http://www.dates.com"
                      elementFormDefault="qualified">
     
    <xsd:element name="details">				
 		<xsd:complexType>
       		<xsd:sequence>	
           		<xsd:element name="name" type="xsd:string" />
                        <xsd:element name="age" type="xsd:positiveInteger" />
                        <xsd:element name="dob" type="xsd:date" />
                        <xsd:element name="year" type="xsd:gYear" />
                        <xsd:element name="month" type="xsd:gMonth" />
                        <xsd:element name="day" type="xsd:gDay" />
                        <xsd:element name="time" type="xsd:time" />
                        <xsd:element name="start" type="xsd:dateTime" />
                        <xsd:element name="period" type="xsd:duration" />							
        	</xsd:sequence>
    	</xsd:complexType>	
	</xsd:element>
</xsd:schema>

=== Akash00226145/sorworkspace/DateTime.xml
<?xml version="1.0" encoding="UTF-8"?>
<details xmlns="http://www.dates.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.dates.com DateTime.xsd">
    <name>Joe Bloggs</name>
    <age>10</age>
    <dob>2007-07-22</dob>
    <year>2007</year>
    <month>--01--</month>
    <day>---22</day>
    <time>10:10:00</time>
    <start>2002-05-20T09:00:00</start>
    <period>P1Y2M3DT10H30M12.0S </period>
</details>
